name = "Permutations"
uuid = "44c39164-0bef-431f-bcd5-f6a8629c17c3"
authors = ["Marcello Vitaletti <marcello.vitaletti@gmail.com>"]
version = "0.0.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
